version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: springbooot-restful
    restart: always
    build: .
    ports:
      - 9095:8081
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: venkat
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
  mysqldb: 
    container_name: mysqldb
    image: mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: venkat
